# Generated by Django 4.0 on 2022-09-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador_examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='frecuencia_pregunta',
            field=models.IntegerField(choices=[('10%', 10), ('25%', 25), ('50%', 50), ('75%', 75), ('100%', 100)], default=100),
        ),
    ]
