# Generated by Django 4.0 on 2022-09-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador_examenes', '0003_alter_pregunta_frecuencia_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('Virtual General', 'Virtual - Práctica'), ('Simulador', 'Simulador')], default='Virtual General', max_length=50),
        ),
    ]
