# Generated by Django 4.0 on 2022-09-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulador_examenes', '0005_alter_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('Virtual Practica', 'Virtual - Practica'), ('Virtual Practica', 'Practica')], default='Virtual General', max_length=50),
        ),
    ]
